import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, fontFamily: inter.style.fontFamily }}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
